### PR TITLE
Improved logging

### PR DESCRIPTION
**Pull request by Torxed**
I've now moved (default value) the log configuration to `storage.py` for a more centralized configuration.
*(The file name is perhaps a bit odd, `settings.py` or something would prooobably make more sense in the long run, and keep storage for storage stuff - for instance session variables etc)*.

This should correct #56 

The change: 
* https://github.com/Torxed/archinstall/blob/40622265a214be0531482ee91ffa61ef2431ae43/archinstall/lib/storage.py#L19-L20

This configuration can be overridden by any installation here:
* https://github.com/Torxed/archinstall/blob/40622265a214be0531482ee91ffa61ef2431ae43/archinstall/lib/installer.py#L44-L47

The install log will contain everything the user sees, except the input (which is reflected in the config which is outputted), here's an example from `/var/log/archinstall/install.log`:

```
-- Guided template chosen (with below config) --
{
    "disk_encryption": true,
    "harddrive": {
        "model": "QEMU_HARDDISK",
        "path": "/dev/sda",
        "size": "8G"
    },
    "hostname": "testmachine",
    "keyboard_layout": "sv-latin1",
    "mirrors": {
        "Sweden": {
            "https://archlinux.dynamict.se/$repo/os/$arch": true,
            "https://ftp.acc.umu.se/mirror/archlinux/$repo/os/$arch": true,
            "https://ftp.lysator.liu.se/pub/archlinux/$repo/os/$arch": true,
            "https://ftp.myrveln.se/pub/linux/archlinux/$repo/os/$arch": true,
            "https://mirror.osbeck.com/archlinux/$repo/os/$arch": true
        }
    },
    "network": {
        "nic": "enp2s0"
    },
    "packages": [
        "nano"
    ],
    "profile": {
        "path": "/root/archinstall-git/profiles/awesome.py"
    },
    "root_unlocked": true,
    "users": [
        "anton"
    ]
}
Adding partition to BlockDevice(/dev/sda)
Adding partition to BlockDevice(/dev/sda)
Formatting Partition(path=/dev/sda1, fs=None, mounted=None) -> fat32
Encrypting Partition(path=/dev/sda2, fs=None, mounted=None) (This might take a while)
Formatting Partition(path=/dev/mapper/luksloop, real_device=/dev/sda2, fs=None, mounted=None) -> btrfs
Mounting Partition(path=/dev/mapper/luksloop, real_device=/dev/sda2, fs=btrfs, mounted=None) to /mnt
Mounting Partition(path=/dev/sda1, fs=fat32, mounted=None) to /mnt/boot
Waiting for automatic mirror selection has completed before using custom mirrors.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Installing packages: ['base', 'base-devel', 'linux', 'linux-firmware', 'efibootmgr', 'nano', 'btrfs-progs']
A new package mirror-list has been created: /mnt/etc/pacman.d/mirrorlist
Adding bootloader systemd-bootctl to Partition(path=/dev/sda1, fs=fat32, mounted=/mnt/boot)
Enabling service systemd-networkd
Enabling service systemd-resolved
Installing packages: ['nano']
Installing network profile Profile(awesome.py)
Installing network profile Profile(xorg)
Installing packages: ('xorg-server xorg-xinit xf86-video-vmware',)
Installing packages: ('awesome xorg-xrandr xterm feh slock terminus-font gnu-free-fonts ttf-liberation xsel',)
Installing packages: ('chromium openssh sshfs git htop pkgfile scrot dhclient wget libu2f-host nemo gpicview-gtk3 nano',)
Installing packages: ('alacritty',)
Creating user anton
Setting password for anton
Setting password for root
Updating /mnt/etc/fstab
Installation completed without any errors. You may now reboot.
```

And here's what it looks like with an error thrown right near the end of an installation:
```
Installing network profile Profile(awesome.py)
Installing packages: ('awesome xorg-xrandr xterm feh slock terminus-font-otb gnu-free-fonts ttf-liberation xsel',)
'/usr/bin/pacstrap /mnt awesome xorg-xrandr xterm feh slock terminus-font-otb gnu-free-fonts ttf-liberation xsel' did not exit gracefully, exit code 256.
==> Creating install root at /mnt
==> Installing packages to /mnt
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
error: target not found: terminus-font-otb
==> ERROR: Failed to install packages to new root
```

Which indicated a faulty package list in `awesome.py` in this case.

Any exception thrown during the installation (either system commands failing or programming errors in the Python code) will be handled by the `__exit__` function of the installer. Custom messages can be thrown to it or default errors will be passed:
* https://github.com/Torxed/archinstall/blob/7eaee2cd4817c1aaca013f8baa267ddf4503f678/archinstall/lib/installer.py#L74-L83

Also added a short info about where to find the log in case it crashes:
* https://github.com/Torxed/archinstall/blob/7eaee2cd4817c1aaca013f8baa267ddf4503f678/archinstall/lib/installer.py#L81-L82

### CODE REVIEW

**Comment by grazzolini** [comment]
Looks fine to me. Just one thing, if the installation fails for whatever reason, before chroot, what happens to the log. It'll be on /var/log/archinstall on the iso or on the mounted system?

**Comment by Torxed** [comment]
> Looks fine to me. Just one thing, if the installation fails for whatever reason, before chroot, what happens to the log. It'll be on /var/log/archinstall on the iso or on the mounted system?

Good catch, the log will be on the ISO in `/var/log/archinstall/install.log` both before and after.
I'll add a copy to the installed medium as well for after-the-fact reporting *(some installations will complete, with minor issues after `archinstall.minimal_installation()`  which could still be bootable, would be nice to have the log there)*.

**Comment by grazzolini** [comment]
Well, I think that, if the installation is successful, copy the log to the actually installed root filesystem. That'll enable easy support. If the installation has failed somehow, then it's ok to have this only on the ISO.

**Comment by Torxed** [comment]
Logs are now copied over to the installed medium during `Installer()` exit (that means both during errors and successfull installation, this will execute):
* https://github.com/Torxed/archinstall/blob/165d4ebc7f420d99eef453b785a86a51ceec8669/archinstall/lib/installer.py#L106-L116

**Pull request merged**
